# top level stuff you probably don't need to touch
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://stevenwante.github.io/
baseurl: /
title: Steven Wante
author: Steven Wante
description: Personal blog and resume
avatar: profile.png
email: me@stevenwante.com
github: stevenwante
twitter: stevenwante
linkedin: stevenwante
#disqus: username
google_analytics: UA-69944665-1